name: Deploy Spring Boot app to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR
        run: ls -lh target/todo.jar

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo "SSH key setup completed"

      - name: Deploy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "target/todo.jar"
          target: "~/"
          strip_components: 1

      - name: Run app on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar ~/todo.jar' || true
            export RDS_URL="${{ secrets.RDS_URL }}"
            export RDS_USERNAME="${{ secrets.RDS_USERNAME }}"
            export RDS_PASSWORD="${{ secrets.RDS_PASSWORD }}"
            nohup java -jar ~/todo.jar > app.log 2>&1 &
            echo "App started in background."
            sleep 10
            if pgrep -f 'java -jar ~/todo.jar' > /dev/null; then
              echo "Application is running successfully"
            else
              echo "Application failed to start. Check app.log for details"
              cat app.log
              exit 1
            fi