name: Deploy App to EC2 + RDS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Create app directory if it doesn't exist
          mkdir -p ~/todo-app
          
          # Copy the JAR file
          scp -i ${{ secrets.EC2_KEY }} ${{ github.workspace }}/target/*.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/todo-app/
          
          # Stop existing application if running
          pkill -f todo-app || true
          
          # Start the application with environment variables
          cd ~/todo-app
          nohup java -jar *.jar \
            --spring.datasource.url=${{ secrets.RDS_URL }} \
            --spring.datasource.username=${{ secrets.RDS_USERNAME }} \
            --spring.datasource.password=${{ secrets.RDS_PASSWORD }} \
            > app.log 2>&1 &
