name: Deploy to AWS EC2         # Basic Workflow for deploying a Java application to AWS EC2

on:
  push:
    branches: [ main ]          # Trigger on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest      # Use the latest Ubuntu runner same way the EC2 instance is set up

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}     # Use secrets for sensitive data
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}       # SSH private key for EC2 access
          source: "target/todo.jar"
          target: "~/app.jar"
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Add EC2 host to known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Check built JAR size
        run: ls -lh target/app.jar
      - name: Copy JAR via scp
        run: scp -i ~/.ssh/id_rsa target/app.jar ubuntu@${{ secrets.EC2_HOST }}:~/app.jar
